(* open Drawing_state.Live_coding *)
(* open Lwd_infix *)
(* open Brr_lwd *)

(* let now () = Brr.Performance.now_ms Brr.G.performance *)

(* let play (editing_state : editing_state) = *)
(*   let max = Lwd.peek editing_state.recording.total_time in *)
(*   let start_time = now () in *)
(*   let rec loop _ = *)
(*     let now = now () -. start_time in *)
(*     Lwd.set editing_state.current_time now; *)
(*     if now <= max then *)
(*       let _animation_frame_id = Brr.G.request_animation_frame loop in *)
(*       () *)
(*     else () *)
(*   in *)
(*   loop 0. *)

(* let replay drawing = *)
(*   let svg = Lwd.observe svg in *)
(*   let on_invalidate _ = *)
(*     let _ : int = *)
(*       Brr.G.request_animation_frame @@ fun _ -> *)
(*       let _ui = Lwd.quick_sample svg in *)
(*       (\* Beware that due to this being ignored, a changed "root" element will *)
(*          not be updated by Lwd, only its reactive attributes/children *\) *)
(*       () *)
(*     in *)
(*     () *)
(*   in *)
(*   let content = *)
(*     Brr.El.find_first_by_selector (Jstr.v "#slipshow-drawing-elem") *)
(*     |> Option.get *)
(*   in *)
(*   Brr.El.prepend_children content [ Lwd.quick_sample svg ]; *)
(*   Lwd.set_on_invalidate svg on_invalidate; *)
(*   () *)
