  $ slipshow compile drawings.md

  $ show_source drawings.html | grep x-data= -A 2 | cut -c 1-250
  <p><span x-data="v1
  This file has been generated by slipshow! The line above gives the version of the syntax for the file, the line below is the actual content. Beware when modifying!
  [[[&quot;id233035159&quot;,1.0009479114190112,[[1305.300321051338,222.66133790137883,504.7607612413343],[1302.993789680826,224.96794670345298,499.44669096206314],[1301.840369132446,226.12125110449006,493.98079010394974],[1299.5338377619337,228.427859

  $ cp drawings.html /tmp/
