  $ slipshow compile drawings.md

  $ show_source drawings.html | grep x-data= -A 2 | cut -c 1-250
  <p><span x-data="v1
  This file has been generated by slipshow! The line above gives the version of the syntax for the file, the line below is the actual content. Beware when modifying!
  [[[&quot;id40677&quot;,1.0010427880976687,[[609.8317985158551,615.4157577483375,685.0999999940395],[608.2106490612632,614.6051830210417,668.6999999880791],[605.7789248793761,612.9840335664499,651.4000000059605],[599.2943270610094,610.5523093845627,63

  $ cp drawings.html /tmp/
