  $ slipshow compile drawings.md

  $ show_source drawings.html | grep x-data= -A 2 | cut -c 1-250
  <p><span x-data="v1
  This file has been generated by slipshow! The line above gives the version of the syntax for the file, the line below is the actual content. Beware when modifying!
  {&quot;events&quot;:[[[&quot;Draw&quot;,[&quot;Continue&quot;,{&quot;coord&quot;:[578.9326679717924,340.69370561233154],&quot;id&quot;:&quot;__slipshow__slipshow_main_pres2_72685752&quot;}]],2546.1954176280406],[[&quot;Draw&quot;,[&quot;Continue&quot

  $ cp drawings.html /tmp/
