We can compile the file using the slip_of_mark binary

  $ slipshow compile pdf.md

The pdf support is added:

  $ show_source pdf.html | grep __pdf_support
      <script id="__pdf_support">// Generated by js_of_ocaml

When no pdf are added, the pdf support code is not added:

  $ slipshow compile no-pdf.md

The pdf support is added:

  $ show_source no-pdf.html | grep __pdf_support
  [1]

$ cp pdf.html /tmp/
